apiVersion: v1
kind: Secret
metadata:
  name: restauranty-secrets
  namespace: restauranty
type: Opaque
stringData:
  CLOUD_NAME: "your-cloudinary-cloud-name"
  CLOUD_API_KEY: "your-cloudinary-api-key"
  CLOUD_API_SECRET: "your-cloudinary-api-secret"
