apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: restauranty-services
  namespace: restauranty
  labels:
    release: monitoring
spec:
  namespaceSelector:
    matchNames:
      - restauranty
  selector:
    matchExpressions:
      - key: app
        operator: In
        values: [auth, discounts, items]
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
